"""Seed the database with realistic Indian research grant data."""

import asyncio
import sys
from datetime import datetime, timezone

sys.path.insert(0, ".")

from app.database import async_session, engine
from app.models import Base
from app.models.grant import Grant
from app.utils.slug import generate_slug

SEED_GRANTS = [
    {
        "agency": "DBT",
        "scheme_name": "BIO-GRID",
        "title": "DBT Biotech Research Infrastructure and Grant for Development (BIO-GRID)",
        "summary": "Major infrastructure grant for creating biotech research networks across India. Supports collaborative research in biotechnology with emphasis on Tier-2/3 institutions.",
        "description": "The Department of Biotechnology invites proposals under the BIO-GRID scheme for establishing biotechnology research clusters. The scheme aims to strengthen biotech research infrastructure at universities and research institutions across India, with special emphasis on institutions in the North-Eastern region and Tier-2/3 cities.",
        "deadline": datetime(2026, 6, 30, tzinfo=timezone.utc),
        "deadline_text": "30/06/2026",
        "budget_min": 10000000,
        "budget_max": 461000000,
        "duration_months": 36,
        "subject_areas": ["Life Sciences", "Biotechnology", "Interdisciplinary"],
        "career_stages": ["Mid Career", "Senior"],
        "institution_types": ["Central University", "State University", "CSIR Lab", "IIT/NIT"],
        "eligibility_summary": "PIs must hold a regular faculty position at a recognized institution. Collaborative proposals involving at least 3 institutions preferred. NE region institutions encouraged.",
        "url": "https://dbtindia.gov.in/schemes-programmes/research-development/bio-grid",
        "notification_url": "https://dbtindia.gov.in/schemes-programmes/research-development/bio-grid",
        "call_url": "https://dbtindia.gov.in/schemes-programmes/research-development/bio-grid",
        "apply_url": "https://epromis.dbt.gov.in",
        "portal_name": "eProMIS",
        "source_type": "manual",
        "status": "active",
    },
    {
        "agency": "DBT",
        "scheme_name": "BioCARe",
        "title": "DBT BioCARe — Biotechnology Career Advancement and Re-orientation Programme for Women Scientists",
        "summary": "Career re-entry grant exclusively for women scientists in biotechnology who have had a career break. Supports independent research projects for up to 3 years.",
        "description": "BioCARe is designed to provide career opportunities to women scientists who have had a break in their career but wish to return to mainstream research in the area of Life Sciences/Biotechnology. The scheme supports individual-centric research projects.",
        "deadline": None,
        "deadline_text": "Open / Rolling",
        "budget_min": 500000,
        "budget_max": 3500000,
        "duration_months": 36,
        "subject_areas": ["Life Sciences", "Biotechnology"],
        "career_stages": ["Early Career", "Mid Career"],
        "institution_types": ["Central University", "State University", "Private", "CSIR Lab"],
        "eligibility_summary": "Open only to women scientists aged 27-57 years with PhD in Life Sciences/Biotechnology. Must have had a career break of at least 2 years. Must have affiliation with a recognized institution.",
        "age_limit": 57,
        "url": "https://dbtindia.gov.in/schemes-programmes/building-capacities/biocare",
        "notification_url": "https://dbtindia.gov.in/schemes-programmes/building-capacities/biocare",
        "call_url": "https://dbtindia.gov.in/schemes-programmes/building-capacities/biocare",
        "apply_url": "https://epromis.dbt.gov.in",
        "portal_name": "eProMIS",
        "source_type": "manual",
        "status": "active",
    },
    {
        "agency": "DST",
        "scheme_name": "WOS-A",
        "title": "DST Women Scientists Scheme-A (WOS-A) for Research in Basic/Applied Sciences",
        "summary": "Research grant for women scientists to pursue independent research in basic or applied sciences. Provides fellowship, research grant, and overhead charges.",
        "description": "The Women Scientists Scheme-A (WOS-A) under DST provides opportunities to women scientists and technologists between the age group of 27-57 years who desire to return to mainstream science and work as bench-level scientists.",
        "deadline": datetime(2026, 4, 30, tzinfo=timezone.utc),
        "deadline_text": "30/04/2026",
        "budget_min": 2000000,
        "budget_max": 3000000,
        "duration_months": 36,
        "subject_areas": ["Life Sciences", "Physical Sciences", "Engineering", "Computer Science"],
        "career_stages": ["Early Career", "Mid Career"],
        "institution_types": ["Central University", "State University", "Private", "CSIR Lab", "IIT/NIT"],
        "eligibility_summary": "Women scientists aged 27-57 years with at least a postgraduate degree in basic or applied sciences. Must have a career break. Must identify a host institution.",
        "age_limit": 57,
        "url": "https://dst.gov.in/scientific-programmes/scientific-engineering-research/women-scientists-programs",
        "notification_url": "https://dst.gov.in/scientific-programmes/scientific-engineering-research/women-scientists-programs",
        "call_url": "https://dst.gov.in/scientific-programmes/scientific-engineering-research/women-scientists-programs",
        "apply_url": "https://onlinedst.gov.in",
        "portal_name": "onlinedst.gov.in",
        "source_type": "manual",
        "status": "active",
    },
    {
        "agency": "DST",
        "scheme_name": "FIST",
        "title": "DST Fund for Improvement of S&T Infrastructure (FIST) — Level I",
        "summary": "Infrastructure development grant for science departments in universities and colleges. Provides equipment, computational facilities, and networking support.",
        "description": "FIST provides basic infrastructure and enabling facilities for teaching and research in science departments. Level I supports departments in colleges and newly established universities. Level II supports university departments with active postgraduate teaching and research.",
        "deadline": datetime(2026, 5, 15, tzinfo=timezone.utc),
        "deadline_text": "15/05/2026",
        "budget_min": 5000000,
        "budget_max": 15000000,
        "duration_months": 60,
        "subject_areas": ["Physical Sciences", "Life Sciences", "Engineering", "Computer Science", "Interdisciplinary"],
        "career_stages": ["Mid Career", "Senior"],
        "institution_types": ["Central University", "State University", "Private"],
        "eligibility_summary": "Science departments in universities and colleges recognized by UGC. Department must have at least 5 regular faculty. Applications are department-level, not individual.",
        "url": "https://dst.gov.in/scientific-programmes/scientific-engineering-research/fund-improvement-st-infrastructure-universities-higher-educational",
        "notification_url": "https://dst.gov.in/scientific-programmes/scientific-engineering-research/fund-improvement-st-infrastructure-universities-higher-educational",
        "call_url": "https://dst.gov.in/scientific-programmes/scientific-engineering-research/fund-improvement-st-infrastructure-universities-higher-educational",
        "apply_url": "https://onlinedst.gov.in",
        "portal_name": "onlinedst.gov.in",
        "source_type": "manual",
        "status": "active",
    },
    {
        "agency": "DST",
        "scheme_name": "PURSE",
        "title": "DST Promotion of University Research and Scientific Excellence (PURSE)",
        "summary": "Performance-based research grant for universities with strong publication records. Supports research infrastructure, equipment, and consumables.",
        "description": "PURSE is a performance-based scheme that supports universities based on their research publication output. The grant aims to strengthen research infrastructure and improve the quality of research at Indian universities.",
        "deadline": datetime(2026, 7, 31, tzinfo=timezone.utc),
        "deadline_text": "31/07/2026",
        "budget_min": 10000000,
        "budget_max": 90000000,
        "duration_months": 48,
        "subject_areas": ["Interdisciplinary"],
        "career_stages": ["Senior"],
        "institution_types": ["Central University", "State University"],
        "eligibility_summary": "Open to universities with significant research output as measured by publication indices. University-level application through the Vice-Chancellor's office.",
        "url": "https://dst.gov.in/scientific-programmes/scientific-engineering-research/promotion-university-research-scientific-excellence",
        "notification_url": "https://dst.gov.in/scientific-programmes/scientific-engineering-research/promotion-university-research-scientific-excellence",
        "call_url": "https://dst.gov.in/scientific-programmes/scientific-engineering-research/promotion-university-research-scientific-excellence",
        "apply_url": "https://onlinedst.gov.in",
        "portal_name": "onlinedst.gov.in",
        "source_type": "manual",
        "status": "active",
    },
    {
        "agency": "ICMR",
        "scheme_name": "Extramural Research",
        "title": "ICMR Extramural Research Programme — Ad-hoc Research Projects",
        "summary": "Individual research grants for biomedical and health research. Supports hypothesis-driven research projects across all areas of health sciences.",
        "description": "The ICMR Extramural Research Programme supports research projects in all areas of biomedical and health research. Ad-hoc research projects are investigator-initiated proposals for hypothesis-driven research.",
        "deadline": None,
        "deadline_text": "Open / Rolling (quarterly review)",
        "budget_min": 500000,
        "budget_max": 5000000,
        "duration_months": 36,
        "subject_areas": ["Medical/Health", "Life Sciences"],
        "career_stages": ["Early Career", "Mid Career", "Senior"],
        "institution_types": ["Central University", "State University", "CSIR Lab", "IIT/NIT"],
        "eligibility_summary": "Regular faculty at recognized medical/research institutions. MD/PhD or equivalent required. Must demonstrate institutional support.",
        "url": "https://www.icmr.gov.in/grants-funding-overview",
        "notification_url": "https://www.icmr.gov.in/grants-funding-overview",
        "call_url": "https://www.icmr.gov.in/grants-funding-overview",
        "apply_url": "https://epms.icmr.org.in",
        "portal_name": "epms.icmr.org.in",
        "source_type": "manual",
        "status": "active",
    },
    {
        "agency": "ICMR",
        "scheme_name": "ICMR-ANVESHAN",
        "title": "ICMR ANVESHAN — Discovery Research Programme for Young Scientists",
        "summary": "Early-career research grant for young biomedical scientists under 40. Supports innovative, high-risk research with mentorship support.",
        "description": "ANVESHAN is ICMR's flagship programme for nurturing young biomedical researchers. It provides research funding along with mentorship from senior scientists for up to 5 years.",
        "deadline": datetime(2026, 5, 31, tzinfo=timezone.utc),
        "deadline_text": "31/05/2026",
        "budget_min": 3000000,
        "budget_max": 7500000,
        "duration_months": 60,
        "subject_areas": ["Medical/Health", "Life Sciences"],
        "career_stages": ["Early Career"],
        "institution_types": ["Central University", "State University", "CSIR Lab", "IIT/NIT"],
        "eligibility_summary": "Scientists below 40 years with PhD/MD in biomedical sciences. Must be in a regular position. Women and SC/ST candidates get 5 years age relaxation.",
        "age_limit": 40,
        "url": "https://www.icmr.gov.in/schemes/anveshan",
        "notification_url": "https://www.icmr.gov.in/schemes/anveshan",
        "call_url": "https://www.icmr.gov.in/schemes/anveshan",
        "apply_url": "https://epms.icmr.org.in",
        "portal_name": "epms.icmr.org.in",
        "source_type": "manual",
        "status": "active",
    },
    {
        "agency": "ANRF",
        "scheme_name": "PM-ECRG",
        "title": "ANRF Prime Minister's Early Career Research Grant (PM-ECRG)",
        "summary": "Flagship early-career grant providing up to ₹2 Cr for 5 years to young researchers within 5 years of PhD. Supports independent, ambitious research.",
        "description": "The PM-ECRG is ANRF's marquee early-career funding scheme, replacing the erstwhile SERB-ECR. It provides substantial funding for young investigators to establish independent research programs across all disciplines of science and engineering.",
        "deadline": datetime(2026, 4, 15, tzinfo=timezone.utc),
        "deadline_text": "15/04/2026",
        "budget_min": 5000000,
        "budget_max": 20000000,
        "duration_months": 60,
        "subject_areas": ["Life Sciences", "Physical Sciences", "Engineering", "Computer Science", "Social Sciences", "Interdisciplinary"],
        "career_stages": ["Early Career"],
        "institution_types": ["Central University", "State University", "Private", "CSIR Lab", "IIT/NIT"],
        "eligibility_summary": "PhD holders within 5 years of PhD award (8 years for women and candidates from NE India). Must be in a regular position at a recognized institution. Age limit: 40 years (45 for women/NE).",
        "age_limit": 40,
        "url": "https://anrf.gov.in/page/english/research_grants",
        "notification_url": "https://anrf.gov.in/page/english/research_grants#PM-ECRG",
        "call_url": "https://anrf.gov.in/page/english/research_grants#ANRF%20Prime%20Minister%27s%20Early%20Career%20Research%20Grant",
        "apply_url": "https://anrfonline.in",
        "portal_name": "anrfonline.in",
        "source_type": "manual",
        "status": "active",
    },
    {
        "agency": "ANRF",
        "scheme_name": "CRG",
        "title": "ANRF Core Research Grant (CRG)",
        "summary": "Investigator-driven research grant for mid-career and senior scientists. Supports frontier research across all science and engineering disciplines.",
        "description": "The Core Research Grant is ANRF's primary scheme for supporting investigator-initiated research. It covers all areas of science and engineering and is open to researchers at all career stages.",
        "deadline": datetime(2026, 8, 31, tzinfo=timezone.utc),
        "deadline_text": "31/08/2026",
        "budget_min": 2000000,
        "budget_max": 10000000,
        "duration_months": 36,
        "subject_areas": ["Life Sciences", "Physical Sciences", "Engineering", "Computer Science", "Interdisciplinary"],
        "career_stages": ["Mid Career", "Senior"],
        "institution_types": ["Central University", "State University", "Private", "CSIR Lab", "IIT/NIT"],
        "eligibility_summary": "Regular faculty at recognized academic institutions and national labs. PhD required. No age limit.",
        "url": "https://anrf.gov.in/page/english/core_research_grant",
        "notification_url": "https://anrf.gov.in/page/english/core_research_grant",
        "call_url": "https://anrf.gov.in/page/english/research_grants#ANRF%20Core%20Research%20Grant",
        "apply_url": "https://anrfonline.in",
        "portal_name": "anrfonline.in",
        "source_type": "manual",
        "status": "active",
    },
    {
        "agency": "ANRF",
        "scheme_name": "MATRICS",
        "title": "ANRF Mathematical Research Impact Centric Support (MATRICS)",
        "summary": "Research grant specifically for mathematical sciences. Provides ₹6.6L per year for 3 years to support theoretical research.",
        "description": "MATRICS supports active researchers in mathematical sciences who are working in areas of national importance. The grant provides flexibility for research expenses, travel, and contingency.",
        "deadline": datetime(2026, 9, 30, tzinfo=timezone.utc),
        "deadline_text": "30/09/2026",
        "budget_min": 660000,
        "budget_max": 660000,
        "duration_months": 36,
        "subject_areas": ["Physical Sciences", "Computer Science"],
        "career_stages": ["Early Career", "Mid Career", "Senior"],
        "institution_types": ["Central University", "State University", "Private", "CSIR Lab", "IIT/NIT"],
        "eligibility_summary": "Active researchers in mathematical sciences with PhD. Must have a regular position at a recognized institution.",
        "url": "https://serb.gov.in/page/english/matrics",
        "notification_url": "https://serb.gov.in/page/english/matrics",
        "call_url": "https://anrf.gov.in/page/english/research_grants#MATRICS",
        "apply_url": "https://anrfonline.in",
        "portal_name": "anrfonline.in",
        "source_type": "manual",
        "status": "active",
    },
    {
        "agency": "ANRF",
        "scheme_name": "SERB-SURE",
        "title": "ANRF SERB-SURE — State University Research Excellence Programme",
        "summary": "Targeted research grant for faculty at state universities. Aims to bridge the research gap between central and state universities.",
        "description": "SERB-SURE is designed to strengthen research at state universities by providing research grants to active faculty. The scheme recognizes the infrastructure challenges at state universities and provides flexible funding.",
        "deadline": None,
        "deadline_text": "Open / Rolling",
        "budget_min": 1000000,
        "budget_max": 3000000,
        "duration_months": 36,
        "subject_areas": ["Life Sciences", "Physical Sciences", "Engineering", "Computer Science"],
        "career_stages": ["Early Career", "Mid Career"],
        "institution_types": ["State University"],
        "eligibility_summary": "Regular faculty at state universities only. PhD required. Must have at least 2 publications in peer-reviewed journals.",
        "url": "https://serb.gov.in/page/english/serb-sure",
        "notification_url": "https://serb.gov.in/page/english/serb-sure",
        "call_url": "https://anrf.gov.in/page/english/research_grants#SERB-SURE",
        "apply_url": "https://anrfonline.in",
        "portal_name": "anrfonline.in",
        "source_type": "manual",
        "status": "active",
    },
    {
        "agency": "BIRAC",
        "scheme_name": "BIG",
        "title": "BIRAC Biotechnology Ignition Grant (BIG)",
        "summary": "Proof-of-concept grant for biotech startups and innovators. Provides up to ₹50L for early-stage translational research and commercialization.",
        "description": "BIG supports innovators and entrepreneurs working on translational research in biotechnology. The scheme funds proof-of-concept studies that can lead to commercializable products or technologies.",
        "deadline": datetime(2026, 5, 15, tzinfo=timezone.utc),
        "deadline_text": "15/05/2026",
        "budget_min": 2000000,
        "budget_max": 5000000,
        "duration_months": 18,
        "subject_areas": ["Life Sciences", "Biotechnology", "Medical/Health"],
        "career_stages": ["Early Career", "Mid Career"],
        "institution_types": ["Central University", "State University", "Private", "CSIR Lab"],
        "eligibility_summary": "Open to Indian nationals with a novel biotech idea. Can be applied individually or as a startup. Must have an incubation partner.",
        "url": "https://birac.nic.in/big.php",
        "notification_url": "https://birac.nic.in/big.php",
        "call_url": "https://birac.nic.in/big.php",
        "apply_url": "https://birac.nic.in/login.php",
        "portal_name": "birac.nic.in",
        "source_type": "manual",
        "status": "active",
    },
    {
        "agency": "BIRAC",
        "scheme_name": "BIPP",
        "title": "BIRAC Biotechnology Industry Partnership Programme (BIPP)",
        "summary": "Industry partnership grant for advanced biotech R&D. Supports 50% of project cost up to ₹20 Cr for industry-academia collaboration.",
        "description": "BIPP supports high-risk, innovative research in biotechnology through industry-academia partnerships. The programme provides partial funding for pre-commercialization research.",
        "deadline": datetime(2026, 6, 15, tzinfo=timezone.utc),
        "deadline_text": "15/06/2026",
        "budget_min": 10000000,
        "budget_max": 200000000,
        "duration_months": 36,
        "subject_areas": ["Life Sciences", "Biotechnology", "Medical/Health"],
        "career_stages": ["Mid Career", "Senior"],
        "institution_types": ["Central University", "State University", "Private", "CSIR Lab", "IIT/NIT"],
        "eligibility_summary": "Indian biotech companies with academia as a partner. Company must contribute at least 50% of project cost. Must have proven R&D capability.",
        "url": "https://birac.nic.in/bipp.php",
        "notification_url": "https://birac.nic.in/bipp.php",
        "call_url": "https://birac.nic.in/bipp.php",
        "apply_url": "https://birac.nic.in/login.php",
        "portal_name": "birac.nic.in",
        "source_type": "manual",
        "status": "active",
    },
    {
        "agency": "CSIR",
        "scheme_name": "EMR",
        "title": "CSIR Extramural Research Scheme",
        "summary": "Research grants for scientists across India in all areas of science and technology. CSIR's primary scheme for supporting investigator-driven research.",
        "description": "The CSIR Extramural Research scheme supports investigator-initiated research projects in all areas of science and technology. The scheme is open to scientists working at universities, academic institutions, and R&D laboratories across India.",
        "deadline": None,
        "deadline_text": "Open / Rolling",
        "budget_min": 500000,
        "budget_max": 3000000,
        "duration_months": 36,
        "subject_areas": ["Life Sciences", "Physical Sciences", "Engineering", "Computer Science", "Interdisciplinary"],
        "career_stages": ["Early Career", "Mid Career", "Senior"],
        "institution_types": ["Central University", "State University", "CSIR Lab", "IIT/NIT"],
        "eligibility_summary": "Regular scientists/faculty at recognized institutions. PhD required. Must submit proposal through proper institutional channel.",
        "url": "https://csirhrdg.res.in/Home/Index/1/Default/2046/57",
        "notification_url": "https://csirhrdg.res.in/Home/Index/1/Default/2046/57",
        "call_url": "https://csirhrdg.res.in/Home/Index/1/Default/2046/57",
        "apply_url": "https://csirhrdg.res.in",
        "portal_name": "csirhrdg.res.in",
        "source_type": "manual",
        "status": "active",
    },
    {
        "agency": "UGC",
        "scheme_name": "Major Research Project",
        "title": "UGC Major Research Project Scheme",
        "summary": "Research grant for university faculty to undertake major research projects. Provides up to ₹15L for science and ₹6L for humanities/social sciences.",
        "description": "UGC Major Research Projects support university faculty in undertaking substantial research over 2-3 years. The scheme covers equipment, travel, contingency, and hiring research staff.",
        "deadline": datetime(2026, 4, 30, tzinfo=timezone.utc),
        "deadline_text": "30/04/2026",
        "budget_min": 300000,
        "budget_max": 1500000,
        "duration_months": 36,
        "subject_areas": ["Life Sciences", "Physical Sciences", "Social Sciences", "Interdisciplinary"],
        "career_stages": ["Mid Career", "Senior"],
        "institution_types": ["Central University", "State University"],
        "eligibility_summary": "Permanent faculty at UGC-recognized universities with PhD and at least 5 years teaching/research experience.",
        "url": "https://www.ugc.gov.in/majorresearchproject",
        "notification_url": "https://www.ugc.gov.in/majorresearchproject",
        "call_url": "https://www.ugc.gov.in/majorresearchproject",
        "apply_url": "https://ugc.gov.in/login",
        "portal_name": "ugc.gov.in",
        "source_type": "manual",
        "status": "active",
    },
    {
        "agency": "UGC",
        "scheme_name": "Start-Up Grant",
        "title": "UGC Faculty Improvement Programme — Start-Up Research Grant for Newly Recruited Faculty",
        "summary": "Start-up grant for newly appointed university faculty. Provides seed funding to establish research laboratories and begin independent research.",
        "description": "The Start-Up Research Grant supports newly recruited university faculty to establish their research programs. It provides essential seed funding for equipment, consumables, and research assistants.",
        "deadline": None,
        "deadline_text": "Open / Rolling",
        "budget_min": 600000,
        "budget_max": 1200000,
        "duration_months": 24,
        "subject_areas": ["Life Sciences", "Physical Sciences", "Engineering", "Social Sciences"],
        "career_stages": ["Early Career"],
        "institution_types": ["Central University", "State University"],
        "eligibility_summary": "Faculty appointed within the last 2 years at UGC-recognized universities. PhD required.",
        "url": "https://www.ugc.gov.in/startupgrant",
        "notification_url": "https://www.ugc.gov.in/startupgrant",
        "call_url": "https://www.ugc.gov.in/startupgrant",
        "apply_url": "https://ugc.gov.in/login",
        "portal_name": "ugc.gov.in",
        "source_type": "manual",
        "status": "active",
    },
    {
        "agency": "AYUSH",
        "scheme_name": "EMR",
        "title": "Ministry of AYUSH Extramural Research Programme",
        "summary": "Research grants for studies in traditional medicine systems — Ayurveda, Yoga, Unani, Siddha, and Homoeopathy.",
        "description": "The Ministry of AYUSH supports research in traditional Indian medicine systems through its Extramural Research Programme. Projects can range from basic research to clinical validation of traditional remedies.",
        "deadline": datetime(2026, 6, 30, tzinfo=timezone.utc),
        "deadline_text": "30/06/2026",
        "budget_min": 500000,
        "budget_max": 5000000,
        "duration_months": 36,
        "subject_areas": ["Medical/Health", "Life Sciences"],
        "career_stages": ["Early Career", "Mid Career", "Senior"],
        "institution_types": ["Central University", "State University", "Private"],
        "eligibility_summary": "Faculty/scientists at recognized AYUSH or medical institutions. Research must relate to AYUSH systems of medicine.",
        "url": "https://main.ayush.gov.in/research",
        "notification_url": "https://main.ayush.gov.in/research",
        "call_url": "https://main.ayush.gov.in/research",
        "apply_url": "https://main.ayush.gov.in",
        "portal_name": "ayush.gov.in",
        "source_type": "manual",
        "status": "active",
    },
    {
        "agency": "ANRF",
        "scheme_name": "ARG",
        "title": "ANRF Accelerate Research Grant (ARG) for Northeast India",
        "summary": "Dedicated research grant for scientists in Northeast India. Provides enhanced funding to address regional disparity in research funding.",
        "description": "ARG-NE is specifically designed to promote research in the eight northeastern states of India. The scheme provides enhanced funding with relaxed eligibility criteria to boost research capacity in the region.",
        "deadline": None,
        "deadline_text": "Open / Rolling",
        "budget_min": 3000000,
        "budget_max": 10000000,
        "duration_months": 36,
        "subject_areas": ["Life Sciences", "Physical Sciences", "Engineering", "Computer Science", "Interdisciplinary"],
        "career_stages": ["Early Career", "Mid Career"],
        "institution_types": ["Central University", "State University", "IIT/NIT"],
        "eligibility_summary": "Faculty at institutions located in NE India (Assam, Arunachal Pradesh, Manipur, Meghalaya, Mizoram, Nagaland, Sikkim, Tripura). PhD required.",
        "url": "https://anrf.gov.in/page/english/arg_ne",
        "notification_url": "https://anrf.gov.in/page/english/arg_ne",
        "call_url": "https://anrf.gov.in/page/english/research_grants#ARG-NE",
        "apply_url": "https://anrfonline.in",
        "portal_name": "anrfonline.in",
        "source_type": "manual",
        "status": "active",
        "is_featured": True,
    },
    {
        "agency": "BIRAC",
        "scheme_name": "PACE",
        "title": "BIRAC Promoting Academic Research Conversion to Enterprise (PACE)",
        "summary": "Grant to help academic researchers convert their research into viable products and startups. Bridges the gap between lab research and market.",
        "description": "PACE supports academic researchers who have promising research outcomes with commercial potential. The programme helps convert academic research into viable commercial enterprises through mentorship and funding.",
        "deadline": datetime(2026, 7, 15, tzinfo=timezone.utc),
        "deadline_text": "15/07/2026",
        "budget_min": 2500000,
        "budget_max": 5000000,
        "duration_months": 24,
        "subject_areas": ["Life Sciences", "Biotechnology", "Medical/Health"],
        "career_stages": ["Early Career", "Mid Career"],
        "institution_types": ["Central University", "State University", "Private", "IIT/NIT"],
        "eligibility_summary": "Academic researchers with protectable IP and demonstrated proof of concept. Must partner with a BIRAC-recognized incubator.",
        "url": "https://birac.nic.in/pace.php",
        "notification_url": "https://birac.nic.in/pace.php",
        "call_url": "https://birac.nic.in/pace.php",
        "apply_url": "https://birac.nic.in/login.php",
        "portal_name": "birac.nic.in",
        "source_type": "manual",
        "status": "active",
    },
]


async def seed():
    """Seed the database with sample grant data."""
    async with async_session() as session:
        for grant_data in SEED_GRANTS:
            title = grant_data["title"]
            agency = grant_data["agency"]
            deadline = grant_data.get("deadline")
            year = deadline.year if deadline else None
            slug = generate_slug(title, agency, year)

            # Check if already exists
            from sqlalchemy import select
            from app.models.grant import Grant

            result = await session.execute(
                select(Grant).where(Grant.slug == slug)
            )
            if result.scalar_one_or_none():
                print(f"  Skipping (exists): {slug}")
                continue

            grant = Grant(slug=slug, **grant_data)
            session.add(grant)
            print(f"  Added: {slug}")

        await session.commit()
        print(f"\nSeeded {len(SEED_GRANTS)} grants.")


if __name__ == "__main__":
    asyncio.run(seed())
